### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Fido789** [birko/SuperFakturaAPI.NET#1]
Pod jakou licencí je ten kód?

**Comment by birko** [comment]
asi MIT. musím si pozrieť ako tie licencie znejú, kto to ma držať stále v hlave :D

**Comment by Fido789** [comment]
Děkuji :)

Ptám se proto, abych věděl, jestli můžu kód využít v pluginu pro eshop klienta, tedy komerčně.

**Comment by birko** [comment]
jaj ta to áno :)  aspoň mi môžeš referovať bugy čo nájdeš.. tiež som to implementoval pre náš projekt. takže je to prototip a mam otestovanú len tu základnú funkčnosť

**Comment by Fido789** [comment]
Skvěle, určitě napíšu, když něco najdu. Díky!

**Comment by birko** [comment]
@Fido789 Taka otazka. sice nie moc na licenciu, ale zistil som ze trsoku musim Refaktorovat zdrojove kody a inak ich restruktualizovat.v priebehu nasedujucich dni. Bude to pre tvoju implemenaciu plugin velky problem alebo sa nemusim obavat?

**Comment by Fido789** [comment]
@birko Díky, že se ptáš, ale samozřejmě to refaktoruj, jak je třeba. Ta moje implementace už je hotová a funguje hezky, takže pokud něco nezmění na samotném API SuperFaktury, tak do toho snad nebudu muset chvilku vrtat.

Jinak díky a dobrá práce!
