### ISSUE TITLE
Bug v metodě GetTags()

### ISSUE THREAD

**Issue by Fido789** [birko/SuperFakturaAPI.NET#3]
Když v SuperFaktuře nejsou nadefinované žádné tagy, tak metoda Client.GetTags() vyhodí exception

Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'System.Collections.Generic.Dictionary`2[System.Int32,System.String]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1.

**Comment by birko** [comment]
Pozrem sa na to. Dakujem

**Comment by birko** [comment]
Vedel by si mi získať celú http response, ktorú dostaneš pri volaní  getTags()?
Na SF nemajú správu tagov a nemozem preto vymazat tagy čo už mám vytvorené

**Comment by Fido789** [comment]
Zrovna teď se k tomu nedostanu, ale jestli se nepletu, bylo to jenom

``` json
[]
```
