### ISSUE TITLE
Invoice.DueDate default value

### ISSUE THREAD

**Issue by Fido789** [birko/SuperFakturaAPI.NET#4]
Ahoj.

U vlastnosti DueDate ve třídě Invoice by asi bylo lepší mít defaultní hodnotu null

```
[JsonProperty(PropertyName = "due", NullValueHandling = NullValueHandling.Ignore)]
public DateTime? DueDate { get; set; } = null;
```

Pak se pro datum splatnosti faktury použije nastavení ze SuperFaktury.

**Comment by birko** [comment]
prihodim v najblizsom commite. spolu s dalsimi upravami v modeli. koli nekonzistencii api odpovedi
