### ISSUE TITLE
Stock.Save - empty item inserted

### ISSUE THREAD

**Issue by jurot8** [birko/SuperFakturaAPI.NET#6]
When I use Stock.Save method, empty records are inserted:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/79969466/207032937-e44ef45d-24bd-4683-b0bc-64c223fd732e.png">

**Comment by birko** [comment]
@jurot8  can ju provide some kind of reqest and response log  (from fiddler or simmilar  network monitor)
